### ISSUE TITLE
Let Users Create New Field Template Groups

### ISSUE THREAD

**Issue by BigActual** [realbigplugins/edd-fields#86]
If you load up a bunch of fields and want to use them repeatedly, shouldn't that be easy? Perhaps have a button in the view that simply states [ + Create Template]

**Comment by d4mation** [comment]
You mean like Field Template Groups?

![image](https://user-images.githubusercontent.com/7770631/48812072-9a565e80-ecfe-11e8-9ce4-e54908368b22.png)

**Comment by BigActual** [comment]
Yes, exactly. I'd like to create a Field Template Group and reuse it.

**Comment by d4mation** [comment]
This is directly supported on the settings page for EDD Fields. I guess I'm confused as to what you're looking for that it cannot do currently.

**Comment by BigActual** [comment]
Yes, but the workflow is not ideal. As an end user with limited knowledge of the extension, I don't know that those settings are available. A user unfamiliar with the product has to know; it's possible, where to do it, and how to do it. Even if they do know, they have to remember that there is a settings page and where to do find it.
If they don't know, they have to go to our docs, read about it, find the multiple links in the EDD workflow to find the settings for Fields and then create the Field Group Templates and then go back to the Downloads to implement them.
I'm suggesting that we skip all of that by just placing a link in the Fields interface, within individual Downloads to create them on the fly. 
![image](https://user-images.githubusercontent.com/8271108/48972126-57dc9c80-eff2-11e8-90ad-e16eb753db4e.png)

**Comment by d4mation** [comment]
We could add a link to the Settings Page there, that'd be fine. But they could not use the Custom (No Template) bit to build out the Field Template Group itself. They function very differently and are not meant to be interchangeable. The Custom Template is meant to be a one-off while Field Template Groups are re-usable and allow you to do more creative things like have a Dropdown of Options to choose from.

**Comment by d4mation** [comment]
This was added in v1.0.2
