### ISSUE TITLE
PHP 7 compatibility issue: count(): Parameter must be an array or an object that implements Countable in class-edd-fields-admin.php on line 468

### ISSUE THREAD

**Issue by davidsherlock** [realbigplugins/edd-fields#87]
When trying to edit a template group, the following error occurs:

`count(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/plugins/edd-fields/core/admin/class-edd-fields-admin.php on line 468`

**Comment by d4mation** [comment]
Thanks for reporting this! Releasing a hotfix now.
